## Example 2 Digit recognition

- Collect : image file provided
- prepare : write a function to convert the image format to the list format that can be used in kNN_Classify0
- analyse : check the prepared data if there are some outliers and possible significant features
- train : no need to apply kNN here
- test : error of text_data
- use : extract digits from an image and use.

00000000000001111111111111111111
00000000000111111111111111111111
00000000000111111111111111111111
00000000001111111111111111111110
00000000000111111111111111111110
00000000000111111111100001111100
00000000000000000000000001111100
00000000000000000000000001111100
00000000000000000000000011111000
00000000000000000000000111111000
00000000000000000000001111110000
00000000000000000000001111100000
00000000000000000000001111100000
00000000000000000000111111000000
00000000000000000000111111000000
00000000000000000111111110000000
00000000000001111111111111000000
00000000000011111111111111100000
00000000000111111111111111000000
00000000000111111111111110000000
00000000001111111111110000000000
00000000000111111111100000000000
00000000000000001111100000000000
00000000000000011111000000000000
00000000000000111111000000000000
00000000000001111110000000000000
00000000000001111110000000000000
00000000000001111110000000000000
00000000000011111100000000000000
00000000000111111000000000000000

```
def img2vec(filename):
    with open(filename,'r') as fr:
        raw_image = fr.readlines()                     # text is a string format
        _nb_row = len(raw_image)
        _nb_col = len(raw_image[0])
        _vec = np.empty(_nb_row * _nb_col)
        for i in range(_nb_row):
            _vec[_nb_col*(i-1) : _nb_col*i] = int(raw_image[i])
    return _vec
    
```

上面这样倒入会产生\n转义字符都被导入的情况。原本32个数字变成33个字符。用readlines的时候，每一行是一个str，这么大的一个数被转成了string。  
同时，不像之前的文件有delimeter(空格，逗号)，这里没有间隔字符。所以只能用strip去掉换行然后转换成list，在用list（）切割转换成np array.

```
def img2vec(filename):
    with open(filename,'r') as fr:
        raw_image = fr.readlines()                     # text is a string format
        vec = []
        for raw in raw_image :
            raw = raw.strip()
            vec.append(np.array(list(''.join(raw)),dtype = 'i4'))
    return vec

```


In [1]:
import kNN

In [2]:
img_vector = kNN.img2vec('/Users/jianghao/Desktop/ML_in_action/MachineLearningInAction-Camp/Week1/digits/trainingDigits/0_4.txt')

In [3]:
img_vector

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0]